// Scans public/ for path folders (each a subdirectory containing .html
// lessons plus an optional _meta.json) and writes src/manifest.js.
// Runs automatically before build/deploy (see [build] in wrangler.toml).
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const PUBLIC_DIR = "public";
const OUTPUT = "src/manifest.js";

function titleFrom(html, fallback) {
  const m = html.match(/<title>([\s\S]*?)<\/title>/i);
  return m ? m[1].trim() : fallback;
}

function titleCase(slug) {
  return slug.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

function readMeta(dirPath) {
  try {
    return JSON.parse(readFileSync(join(dirPath, "_meta.json"), "utf8"));
  } catch {
    return {};
  }
}

const paths = readdirSync(PUBLIC_DIR, { withFileTypes: true })
  .filter((entry) => entry.isDirectory())
  .map((entry) => {
    const dirPath = join(PUBLIC_DIR, entry.name);
    const meta = readMeta(dirPath);

    const lessons = readdirSync(dirPath)
      .filter((f) => f.endsWith(".html"))
      .sort()
      .map((f) => {
        const html = readFileSync(join(dirPath, f), "utf8");
        return { path: `${entry.name}/${f}`, title: titleFrom(html, f) };
      });

    return {
      slug: entry.name,
      title: meta.title || titleCase(entry.name),
      description: meta.description || "",
      order: meta.order ?? 0,
      lessons,
    };
  })
  .sort((a, b) => a.order - b.order || a.title.localeCompare(b.title));

const banner = "// AUTO-GENERATED by build-index.js -- do not edit by hand.\n";
writeFileSync(
  OUTPUT,
  banner + "export const paths = " + JSON.stringify(paths, null, 2) + ";\n"
);

const lessonCount = paths.reduce((n, p) => n + p.lessons.length, 0);
console.log(`Wrote ${OUTPUT} with ${paths.length} path(s), ${lessonCount} lesson(s).`);
