// Scans public/ for path folders (each a subdirectory containing .html
// lessons plus an optional _meta.json) and writes src/manifest.js.
// Runs automatically before build/deploy (see [build] in wrangler.toml).
// With --watch it stays running and rewrites the manifest whenever the
// contents of public/ change (see the dev script in package.json).
import { readdirSync, readFileSync, writeFileSync, watch } from "node:fs";
import { join } from "node:path";

const PUBLIC_DIR = "public";
const OUTPUT = "src/manifest.js";

function titleFrom(html, fallback) {
  const m = html.match(/<title>([\s\S]*?)<\/title>/i);
  return m ? m[1].trim() : fallback;
}

function titleCase(slug) {
  return slug.replace(/-/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

function readMeta(dirPath) {
  try {
    return JSON.parse(readFileSync(join(dirPath, "_meta.json"), "utf8"));
  } catch {
    return {};
  }
}

function scan() {
  return readdirSync(PUBLIC_DIR, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => {
      const dirPath = join(PUBLIC_DIR, entry.name);
      const meta = readMeta(dirPath);

      const lessons = readdirSync(dirPath)
        .filter((f) => f.endsWith(".html"))
        .sort()
        .map((f) => {
          const html = readFileSync(join(dirPath, f), "utf8");
          return { path: `${entry.name}/${f}`, title: titleFrom(html, f) };
        });

      return {
        slug: entry.name,
        title: meta.title || titleCase(entry.name),
        description: meta.description || "",
        order: meta.order ?? 0,
        lessons,
      };
    })
    .sort((a, b) => a.order - b.order || a.title.localeCompare(b.title));
}

// Writes the manifest and reports it, unless the scan produced exactly what
// is already on disk -- an unchanged write would restart the dev server for
// an edit that never reached the index.
function build() {
  const paths = scan();
  const banner = "// AUTO-GENERATED by build-index.js -- do not edit by hand.\n";
  const contents =
    banner + "export const paths = " + JSON.stringify(paths, null, 2) + ";\n";

  let current = "";
  try {
    current = readFileSync(OUTPUT, "utf8");
  } catch {
    // no manifest yet
  }
  if (current === contents) return;

  writeFileSync(OUTPUT, contents);

  const lessonCount = paths.reduce((n, p) => n + p.lessons.length, 0);
  console.log(`Wrote ${OUTPUT} with ${paths.length} path(s), ${lessonCount} lesson(s).`);
}

build();

if (process.argv.includes("--watch")) {
  // fs.watch fires several times for one save, so coalesce a burst into a
  // single rebuild.
  let pending = null;

  watch(PUBLIC_DIR, { recursive: true }, () => {
    clearTimeout(pending);
    pending = setTimeout(build, 50);
  });

  console.log(`Watching ${PUBLIC_DIR}/ for changes.`);
}
