// Scans public/ for .html files and writes src/manifest.js.
// Runs automatically before build/deploy (see [build] in wrangler.toml).
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const PUBLIC_DIR = "public";
const OUTPUT = "src/manifest.js";

function titleFrom(html, fallback) {
  const m = html.match(/<title>([\s\S]*?)<\/title>/i);
  return m ? m[1].trim() : fallback;
}

const entries = readdirSync(PUBLIC_DIR)
  .filter((f) => f.endsWith(".html") && f !== "404.html")
  .sort()
  .map((f) => {
    const html = readFileSync(join(PUBLIC_DIR, f), "utf8");
    return { path: f, title: titleFrom(html, f) };
  });

const banner = "// AUTO-GENERATED by build-index.js -- do not edit by hand.\n";
writeFileSync(
  OUTPUT,
  banner + "export const files = " + JSON.stringify(entries, null, 2) + ";\n"
);

console.log(`Wrote ${OUTPUT} with ${entries.length} file(s).`);
