// AUTO-GENERATED by build-index.js -- do not edit by hand.
export const paths = [
  {
    "slug": "core-javascript",
    "title": "Core JavaScript",
    "description": "Modern ES Modules and functional patterns, for developers coming from namespace- and class-driven TypeScript.",
    "order": 1,
    "lessons": [
      {
        "path": "core-javascript/01-module-scope.html",
        "title": "Module Scope"
      },
      {
        "path": "core-javascript/02-closures-instead-of-classes.html",
        "title": "Closures Instead of Classes"
      },
      {
        "path": "core-javascript/03-replacing-static-members.html",
        "title": "Replacing Static Members and Singletons"
      },
      {
        "path": "core-javascript/04-functions-over-classes.html",
        "title": "Functions Over Classes"
      },
      {
        "path": "core-javascript/05-pure-functions-and-immutability.html",
        "title": "Pure Functions and Immutability"
      },
      {
        "path": "core-javascript/06-composition-over-inheritance.html",
        "title": "Composition Over Inheritance"
      },
      {
        "path": "core-javascript/07-dynamic-imports.html",
        "title": "Dynamic import()"
      },
      {
        "path": "core-javascript/08-case-study-refactor.html",
        "title": "Case Study: Refactoring a Namespace Class"
      },
      {
        "path": "core-javascript/09-exports-and-barrel-patterns.html",
        "title": "Exports and Barrel Patterns"
      }
    ]
  },
  {
    "slug": "react",
    "title": "React",
    "description": "Crossframe work communication - useSyncExternalStore / delegate patterns",
    "order": 2,
    "lessons": [
      {
        "path": "react/01-the-external-store.html",
        "title": "The External Store"
      },
      {
        "path": "react/02-use-sync-external-store.html",
        "title": "useSyncExternalStore"
      },
      {
        "path": "react/03-lazy-loading-components.html",
        "title": "Lazy Loading Components"
      },
      {
        "path": "react/04-suspense.html",
        "title": "Suspense"
      },
      {
        "path": "react/05-error-boundaries.html",
        "title": "Error Boundaries"
      }
    ]
  }
];
