// AUTO-GENERATED by build-index.js -- do not edit by hand.
export const files = [
  { "path": "lesson-1.html", "title": "Lesson 1: Getting Started" },
  { "path": "lesson-2.html", "title": "Lesson 2: Next Steps" }
];
